Tagpub/TagPub/urls.py
from django.contrib import admin
from django.urls import path, include
from tagpubDev.views import index, userLogout, TagAutocomplete


urlpatterns = [
    path('', index, name='home'),
    path('tagpub/', include('tagpubDev.urls')),
    path('admin/', admin.site.urls),
    path('logout/', userLogout, name='logout'),
    path('tag-autocomplete/', TagAutocomplete.as_view(), name='tag-autocomplete'),
]

Tagpub/tagpubDev/urls.py
from django.urls import path
from tagpubDev import views

app_name = 'tagpubDev'

urlpatterns = [
    path('', views.index, name='index'),
    path('registration/', views.registration, name='registration'),
    path('articleDetail/<int:pk>', views.articleDetail, name='articleDetail'),
    path('registrationRequests/', views.registrationRequests, name='registrationRequests'),
    path('userLogin/', views.userLogin, name='userLogin'),
    path('tagList/', views.tagsList, name='tag_list'),
    path('userList/', views.userList, name='userList'),
    path('userProfile/', views.userProfile, name='userProfile'),
]

Tagpub/tagpubDev/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
# from django.contrib.postgres.fields import ArrayField
from django.contrib.postgres.search import SearchVectorField, SearchVector
# import tsvector_field
# Create your models here.


class RegistrationApplication(models.Model):
    applicationStatuses = (
        ('1', 'New'),
        ('2', 'Approved'),
        ('3', 'Rejected')
    )

    name = models.CharField(max_length=64)
    surname = models.CharField(max_length=64)
    email = models.EmailField()
    applicationText = models.TextField(max_length=512)
    applicationDate = models.DateTimeField(default=timezone.now)
    applicationStatus = models.CharField(max_length=20, choices=applicationStatuses, default='1')


class UserProfileInfo(models.Model):

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    adminStatus = models.BooleanField(default=False)
    # pip install pillow to use this!
    # Optional: pip install pillow --global-option="build_ext" --global-option="--disable-jpeg"
    # profile_pic = models.ImageField(upload_to='basic_app/profile_pics',blank=True)
    registrationApplication = models.ForeignKey(RegistrationApplication, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Journal(models.Model):

    ISSN = models.CharField(max_length=16)
    Title = models.CharField(max_length=256)
    ISOAbbreviation = models.CharField(max_length=256)

    def __str__(self):
        return self.Title


class Author(models.Model):

    LastName = models.CharField(max_length=128)
    ForeName = models.CharField(max_length=128, null=True)
    Initials = models.CharField(max_length=8)

    def __str__(self):
        return self.ForeName + ' ' + self.LastName


class Keyword(models.Model):

    KeywordText = models.TextField(max_length=64)

    def __str__(self):
        return self.KeywordText


class Tag(models.Model):
    TagName = models.CharField(max_length=64, default='noname')
    WikiID = models.CharField(max_length=64)
    Label = models.CharField(max_length=64)
    Description = models.TextField(max_length=1024, null=True)
    # Maybe an array field for tokens?
    Tokens = models.TextField(max_length=1024, null=True)
    SearchIndex = SearchVectorField(null=True)

    def createTSvector(self, *args, **kwargs):
        self.SearchIndex = (
                SearchVector('Label', weight='A')
                + SearchVector('Tokens', weight='B')
                + SearchVector('Description', weight='C')
        )
        super().save(*args, **kwargs)


class Article(models.Model):

    PMID = models.CharField(max_length=16)
    Title = models.TextField(max_length=512)
    Abstract = models.TextField(max_length=5000, null=True)
    PublicationDate = models.DateField(null=True)

    Journal = models.ForeignKey(Journal, on_delete=models.PROTECT, null=True)
    Keywords = models.ManyToManyField(Keyword)
    Authors = models.ManyToManyField(Author)
    Tags = models.ManyToManyField(Tag)

    # Tokens = ArrayField(
    #     models.CharField(max_length=128),
    #     size=128
    # )

    Tokens = models.TextField(max_length=100000)

    SearchIndex = SearchVectorField(null=True)

    def createTSvector(self, *args, **kwargs):
        self.SearchIndex = (
                SearchVector('PMID', weight='A')
                + SearchVector('Title', weight='A')
                + SearchVector('Abstract', weight='B')
                + SearchVector('Tokens', weight='C')
        )
        super().save(*args, **kwargs)

    def __str__(self):
        return self.Title


# class Article(models.Model):
#
#     ActorType = models.CharField(max_length=16)
#     ActorID = models.TextField(max_length=512)
#     ActorName = models.TextField(max_length=5000, null=True)
#     PublicationDate = models.DateField(null=True)
#
#     Journal = models.ForeignKey(Journal, on_delete=models.PROTECT, null=True)
#     Keywords = models.ManyToManyField(Keyword)
#     Authors = models.ManyToManyField(Author)
#     Tags = models.ManyToManyField(Tag)
#
#
#     def __str__(self):
#         return self.Title

Tagpub/tagpubDev/forms.py
from django import forms
# from django.contrib.auth.models import User
from tagpubDev.models import RegistrationApplication
from dal import autocomplete


class ApplicationRegistrationForm(forms.ModelForm):

    class Meta:
        model = RegistrationApplication
        fields = ('name', 'surname', 'email', 'applicationText')


class TagForm(forms.Form):
    wikiLabel = autocomplete.Select2ListChoiceField(
        widget=autocomplete.ListSelect2(url='tag-autocomplete'),
        label="Search Wikidata Entry"
    )

Tagpub/tagpubDev/views.py
from dal import autocomplete
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from tagpubDev.forms import ApplicationRegistrationForm, TagForm
from tagpubDev.models import RegistrationApplication, UserProfileInfo, User, Article, Author, Tag, Keyword
from tagpubDev.utils.wikiManager import getLabelSuggestion, WikiEntry
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from tagpubDev.utils.data import SearchResult


def index(request):
    if request.method == 'POST':
        search_terms = request.POST.get('searchTerms').split(",")

        search = SearchResult(search_terms)
        results_list = search.getSearchResults()

        page = request.POST.get('page', 1)
        paginator = Paginator(results_list, 25)
        search_str = request.POST.get('searchTerms')
        try:
            results = paginator.page(page)
        except PageNotAnInteger:
            results = paginator.page(1)
        except EmptyPage:
            results = paginator.page(paginator.num_pages)

        date_data = search.getYearlyArticleCounts()

        results_dict = {"results_list": results,
                        "search_term": search_str,
                        "date_labels": date_data.keys(),
                        "data_values": date_data.values()
                        }
        return render(request, 'tagpubDev/searchResults.html', context=results_dict)
    else:
        if request.GET.get('page', False):
            page = request.GET.get('page')
            search_terms = request.GET.get('term').split(",")

            results_list = SearchResult(search_terms).getSearchResults()

            paginator = Paginator(results_list, 25)
            search_str = request.GET.get('term')
            try:
                results = paginator.page(page)
            except PageNotAnInteger:
                results = paginator.page(1)
            except EmptyPage:
                results = paginator.page(paginator.num_pages)
            results_dict = {"results_list": results,
                            "search_term": search_str
                            }
            return render(request, 'tagpubDev/searchResults.html', context=results_dict)
        else:
            return render(request, 'tagpubDev/index.html')


def registration(request):
    if request.method == 'POST':
        registration_form = ApplicationRegistrationForm(data=request.POST)
        if registration_form.is_valid():
            if RegistrationApplication.objects.filter(email=request.POST['email']).filter(applicationStatus='1').exists():
                return HttpResponse('application under review')

            else:
                registration_form.save()
                return HttpResponse('applications received')
        else:
            print(registration_form.errors)
    else:
        registration_form = ApplicationRegistrationForm()

    return render(request, 'tagpubDev/registration.html',
                  {'registration_form': registration_form})


@login_required
def registrationRequests(request):
    if request.method == 'POST':
        approved_request = RegistrationApplication.objects.get(pk=request.POST['request_id'])
        approved_request.applicationStatus = '2'
        approved_request.save()
        user = User(username=approved_request.email,
                    first_name=approved_request.name,
                    last_name=approved_request.surname,
                    email=approved_request.email,
                    password='TestPwd123')
        user.set_password(user.password)
        user.save()
        user_profile = UserProfileInfo(registrationApplication_id=approved_request.id, user_id=user.id)
        user_profile.save()

    requests_list = RegistrationApplication.objects.filter(applicationStatus='1').order_by('applicationDate')
    requests_dict = {"registration_requests": requests_list}
    return render(request, 'tagpubDev/registrationRequests.html', context=requests_dict)


def userLogin(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('tagpubDev:index'))
            else:
                return HttpResponse("Your account is not active.")
        else:
            print("login failed username: {} and password: {}".format(username, password))
            return HttpResponse("Invalid login details")

    else:
        return render(request, 'tagpubDev/login.html', {})


@login_required
def userList(request):
    if request.method == 'POST':
        if 'user_id' in request.POST:
            removed_user = User.objects.get(pk=request.POST['user_id'])
            removed_user.is_active = False
            removed_user.save()
        elif 'admin_status' in request.POST:
            admin_user = User.objects.get(pk=request.POST['admin_status'])
            admin_user.userprofileinfo.adminStatus = not admin_user.userprofileinfo.adminStatus
            admin_user.userprofileinfo.save()

    users = User.objects.filter(is_active=True)
    cur_username = request.user.username
    admin_status = User.objects.filter(username=cur_username).values_list('userprofileinfo__adminStatus')
    print(admin_status[0][0])
    return render(request, 'tagpubDev/userList.html', {'user_list': users, 'admin': admin_status[0][0]})


def userProfile(request):
    if request.method == 'POST':
        username = request.user.username
        password = request.POST.get('password')
        user = User.objects.get(username=username)
        user.set_password(password)
        user.save()

    return render(request, 'tagpubDev/userProfile.html', {})


@login_required
def userLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('tagpubDev:userLogin'))

@login_required
def articleDetail(request, pk):
    article = Article.objects.get(pk=pk)
    wiki_info = {}
    if request.method == 'POST':
        if 'get_tag' in request.POST:
            tag_form = TagForm(data=request.POST)
            tag_data = WikiEntry(tag_form.data['wikiLabel'])
            wiki_info['qid'] = tag_data.getID()
            wiki_info['label'] = tag_data.getLabel()
            wiki_info['description'] = tag_data.getDescription()
            wiki_info['existing_tags'] = Tag.objects.filter(WikiID=tag_data.getID())
        elif 'add_tag' in request.POST:
            tag_data = WikiEntry(request.POST['qid'])
            tag, created = Tag.objects.get_or_create(WikiID=tag_data.getID(), Label=tag_data.getLabel(), TagName=request.POST['tag_name'])
            if created:
                tag.Description = tag_data.getDescription()
                tag.Tokens = tag_data.getTokens()
                tag.save()
                tag.createTSvector()
                article.Tags.add(tag)
            else:
                article.Tags.add(tag)
        elif 'tag_id' in request.POST:
            tag = Tag.objects.get(pk=request.POST['tag_id'])
            print(request.POST['tag_id'])
            article.Tags.remove(tag)

    tag_form = TagForm()
    authors = Author.objects.filter(article=article)
    keywords = Keyword.objects.filter(article=article)
    keywords_list = ', '.join([item.KeywordText for item in keywords])
    tags = Tag.objects.filter(article=article)
    article_dict = {"authors": authors,
                    "title": article.Title,
                    "abstract": article.Abstract,
                    "pmid": article.PMID,
                    "tag_form": tag_form,
                    "keywords": keywords_list,
                    "tags": tags
                    }

    article_dict.update(wiki_info)

    return render(request, 'tagpubDev/articleDetail.html', context=article_dict)


class TagAutocomplete(autocomplete.Select2ListView):

    def get_list(self):
        taglist = getLabelSuggestion(self.q)
        return taglist

@login_required
def tagsList(request):

    tag_list = Tag.objects.all()

    return render(request, 'tagpubDev/tagList.html',
                  {'tag_list': tag_list})

Tagpub/templates/tagpubDev/articleDetail.html
{% extends 'tagpubDev/base.html' %}
{% load static %}

{% block body_block %}
    {% load crispy_forms_tags %}
    <div class="container py-4">

        <div class="p-5 mb-4 bg-light border rounded-3 ">
            <h3>{{ title }}</h3>
            <p><span class="fw-bold">Authors: </span>
                {% for item in authors %}
                    {% if forloop.last %}
                        {{ item.ForeName }} {{ item.LastName }}
                    {% else %}
                        {{ item.ForeName }} {{ item.LastName }},
                    {% endif %}
                {% endfor %}
            </p>
            <div class="container">
                <div class="row">
                    <div class="col">PMID: <a href="https://pubmed.ncbi.nlm.nih.gov/{{ pmid }}">{{ pmid }}</a></div>
                </div>
            </div>
            <hr>
            <p class="fw-bold">Abstract</p>
            <p>{{ abstract }}</p>
            <p class="fw-bold">Keywords</p>
            <p>{{ keywords }}</p>
            <hr>
            <p class="fw-bold">Tags</p>
            <table class="table table-striped">
                <tr>
                    <th>ID</th>
                    <th>Q code</th>
                    <th>System Name</th>
                    <th>Label</th>
                    <th>Description</th>
                    <th>Remove</th>

                </tr>
                {% for item in tags %}
                    <tr>
                        <td><a href="{% url 'tagpubDev:articleDetail' item.id %}">{{ item.id }}</a></td>
                        <td><a href="https://www.wikidata.org/wiki/{{ item.WikiID }}">{{ item.WikiID }}</a></td>
                        <td>{{ item.TagName }}</td>
                        <td>{{ item.Label }}</td>
                        <td>{{ item.Description }}</td>
                        <td>
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" value="{{ item.id }}" name="tag_id">
                                <button class="confirm_action" type="Submit">X</button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </table>
            <hr>
            <div class="container-fluid py-4">
                <form class="tagForm" method="post">
                    {% csrf_token %}
                    {{ tag_form|crispy }}
                    <div id="searchHelp" class="form-text">Search for wikidata entry using labels or Q codes</div>
                    <input class="register-button" type="submit" name="get_tag" value="Get Tag">

                </form>
            <hr>
                {% if qid %}
                    {% if existing_tags %}
                    <p>Click on an existing tag to use it.</p>
                    <table class="table table-striped">
                        <tr>
                            <th>Existing Tags</th>
                        </tr>
                        {% for item in existing_tags %}
                            <tr>
                                <td class="tag_name">{{ item.TagName }}</td>
                            </tr>
                        {% endfor %}
                    </table>
                        {% endif %}
                    <div class="container-fluid">
                        <form method="post">
                            {% csrf_token %}
                            <label for="tag_name">Tag Name:</label>
                            <input id="tag_name" type="text" name="tag_name" required>
                            <p></p>
                            <label for="qid">Entry ID:</label>
                            <input type="text" name="qid" value="{{ qid }}" readonly>
                            <p></p>
                            <label for="label">Label:</label>
                            <textarea type="text" name="label" cols="80" rows="1" readonly>{{ label }}</textarea>
                            <p></p>
                            <label for="description">Description:</label>
                            <textarea type="text" name="description" cols="80" rows="5"
                                      readonly>{{ description }}</textarea>
                            <p></p>
                            <div id="searchHelp" class="form-text">Save and add tag</div>
                            <input class="register-button" type="submit" name="add_tag" value="Add Tag">

                        </form>
                    </div>

                {% endif %}
            </div>

            <script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

            {{ tag_form.media }}

            <script>
                (function ($) {
                    $('#add-form').click(function () {
                        var index = $('#id_inline_test_models-TOTAL_FORMS').val()
                        var newTable = $('#id_inline_test_models-__prefix__-DELETE').parents('table').clone()
                        newTable.find(':input').each(function () {
                            for (attr of ['name', 'id'])
                                $(this).attr(
                                    attr,
                                    $(this).attr(attr).replace('__prefix__', index)
                                )
                        })
                        newTable.insertBefore($(this))
                        $('#id_inline_test_models-TOTAL_FORMS').val(
                            parseInt($('#id_inline_test_models-TOTAL_FORMS').val()) + 1
                        )
                        newTable.slideDown()
                    })
                })($)
            </script>
        </div>
    </div>

{% endblock %}

Tagpub/templates/tagpubDev/base.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Semih Solmaz">
    <title>Article Tagging</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/grid/">
    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/navbars/">

    <!-- Bootstrap-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf"
            crossorigin="anonymous"></script>

    <!-- JQuery-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js"
            integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css"
          integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous"/>

    <!--Font Awesome library-->
    <script src="https://kit.fontawesome.com/f405fd37c0.js" crossorigin="anonymous"></script>

    <!-- Custom styles for this template -->
    <link href="{% static 'tagpubDev/css/grid.css' %}" rel="stylesheet">
    <link href="{% static 'tagpubDev/css/navbar.css' %}" rel="stylesheet">
    <link href="{% static 'tagpubDev/css/bootstrap-tagsinput.css' %}" rel="stylesheet">
    <link href="{% static 'tagpubDev/css/styles.css' %}" rel="stylesheet">
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark" aria-label="Fourth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'tagpubDev:index' %}">TagPub</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExample04"
                aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample04">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'tagpubDev:index' %}">Home</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'tagpubDev:tag_list' %}">Tags</a>
                    </li>

                    <li>
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'tagpubDev:userList' %}">Users</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'tagpubDev:userProfile' %}">Profile</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'tagpubDev:tag_list' %}">Tags</a>
                    </li>
                {% else %}
                    <li>
                        <a class="nav-link" href="{% url 'tagpubDev:userLogin' %}">Login</a>
                    </li>
                    <li>
                        <a class="nav-link" href="{% url 'tagpubDev:registration' %}">Register</a>
                    </li>
                {% endif %}
            </ul>
            <!--            <form>-->
            <!--                <input class="form-control" type="text" placeholder="Search" aria-label="Search">-->
            <!--            </form>-->
        </div>
    </div>
</nav>

{% block body_block %}

{% endblock %}
<footer class="mastfoot mt-auto text-center py-4">
    <div class="inner">
        <p>Pubmed Article tagging application by Semih Solmaz <span class="mt-5 mb-3 text-muted">© 2021</span></p>
    </div>
</footer>


<script src="{% static 'tagpubDev/js/bootstrap-tagsinput.js' %}"></script>
<script src="{% static 'tagpubDev/js/index.js' %}"></script>
</body>
</html>

Tagpub/templates/tagpubDev/index.html
{% extends 'tagpubDev/base.html' %}

{% block body_block %}
    <div class="container py-4">
      <div class="p-5 mb-4 bg-light border rounded-3 ">
        <div class="container-fluid py-2 text-center">
            <form class="searchForm noEnter" method="post">
                {% csrf_token %}
              <label for="searchField" class="form-label"><span class="fw-bold">Search: </span></label>
              <input id="searchField" class="form-control form-control-lg" type="text" value="" data-role="tagsinput" placeholder="Enter keywords" name="searchTerms"/>
              <div id="searchHelp" class="form-text">Search articles with multiple keywords.</div>
              <input id="basicSearchButton" type="submit" class="btn btn-primary" value="Search"></input>
            </form>
        </div>
      </div>
    </div>

{% endblock %}

Tagpub/templates/tagpubDev/login.html
{% extends 'tagpubDev/base.html' %}

{% block body_block %}

    <div class="container text-center">
        <div class="row">
            <div class="col-md"></div>
            <div class="col-md">
                <form class="form-div" method="post" action="{% url 'tagpubDev:userLogin' %}">
                    {% csrf_token %}
                    <label for="username">Email:</label>
                    <input type="text" name="username" placeholder="Username">
                    <p></p>
                    <label for="password">Password:</label>
                    <input type="password" name="password">
                    <div id="searchHelp" class="form-text">Login using email and password</div>
                    <input type="submit" name="" value="Login">
                </form>
            </div>
            <div class="col-md"></div>
        </div>

    </div>

{% endblock %}

Tagpub/templates/tagpubDev/searchResults.html
{% extends 'tagpubDev/base.html' %}
{% load static %}

{% block body_block %}
    <div class="container">
<canvas id="myChart" width="100" height="30"></canvas>
    </div>

    <div class="container">
        <h3 class="lead">Search Results</h3>
        <table class="table table-striped">
            <tr>
                <th>PMID</th>
                <th>Title</th>
                <th>Date</th>

            </tr>
            {% for item in results_list %}
                <tr>
                    <td><a href="{% url 'tagpubDev:articleDetail' item.id %}">{{ item.id }}</a></td>
                    <td>{{ item.Title }}</td>
                    <td>{{ item.PublicationDate }}</td>
                </tr>
            {% endfor %}
        </table>

        {% if results_list.has_other_pages %}
            <ul class="pagination">
                {% if results_list.has_previous %}
                    <li class="page-item"><a class="page-link" href="?page={{ results_list.previous_page_number }}&term={{ search_term }}">&laquo;</a></li>
                {% else %}
                    <li class="disabled page-item"><span class="page-link">&laquo;</span></li>
                {% endif %}
                {% for i in results_list.paginator.page_range %}
                    {% if results_list.number == i %}
                        <li class="active page-item"><span class="page-link">{{ i }} <span class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}&term={{ search_term }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if results_list.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ results_list.next_page_number }}&term={{ search_term }}">&raquo;</a></li>
                {% else %}
                    <li class="disabled page-item"><span class="page-link">&raquo;</span></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>

        <script>


var ctx2 = document.getElementById('myChart');
var myChart = new Chart(ctx2, {
    type: 'bar',
    data: {
        labels: [{% for item in date_labels %}'{{ item }}',{% endfor %}],
        datasets: [{
            label: '# of Articles',
            data: [{% for item in data_values %}'{{ item }}',{% endfor %}],
            borderWidth: 1
        }]
    },
    options: {
        scales: {
            y: {
                beginAtZero: true
            }
        }
    }
});
</script>

{% endblock %}

{% block script_block %}



{% endblock %}

Tagpub/templates/tagpubDev/userList.html
{% extends 'tagpubDev/base.html' %}
{% load static %}

{% block body_block %}
<a href="{% url 'tagpubDev:registrationRequests' %}">Click to view registration requests</a>
    <div class="container">
        <h3 class="lead">Users</h3>
        <table class="table table-striped">
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Surname</th>
                <th>Email</th>
                {% if admin %}
                <th>Admin Status</th>
                <th>Remove</th>
                {% endif %}

            </tr>
            {% for item in user_list %}
                <tr>
                    {#                    <td><a href="{% url 'tagpubDev:articleDetail' item.id %}">{{ item.id }}</a></td>#}
                    <td>{{ item.id }}</td>
                    <td>{{ item.first_name }}</td>
                    <td>{{ item.last_name }}</td>
                    <td>{{ item.email }}</td>
                    {% if admin %}
                    <td>
                        {% if item.userprofileinfo.adminStatus %}
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" value="{{ item.id }}" name="admin_status">
                                <button class="confirm_action" type="Submit">Remove admin status</button>
                            </form>
                        {% else %}
                            <form method="POST">
                                {% csrf_token %}
                                <input type="hidden" value="{{ item.id }}" name="admin_status">
                                <button class="confirm_action" type="Submit">Make admin</button>
                            </form>
                        {% endif %}
                    </td>
                    <td>
                        <form method="POST">
                            {% csrf_token %}
                            <input type="hidden" value="{{ item.id }}" name="user_id">
                            <button class="confirm_action" type="Submit">Delete</button>
                        </form>
                    </td>
                {% endif %}
                </tr>
            {% endfor %}
        </table>
    </div>

{% endblock %}